name: Pull Requests Handling

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      name: rc to master
      if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'rc' }}
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: hmarr/auto-approve-action@v2.0.0
      name: release to master
      if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'release' }}
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

  rc_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.base.ref == 'rc' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            rc
        
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'rc' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automerge
            
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'release' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automerge
